<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>1.0.0</Version>
	<Authors>hedonghua</Authors>
	<Description>Orleans配置,Redis集群,Redis存储</Description>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="9.2.1" />
		<PackageReference Include="Microsoft.Orleans.Persistence.Redis" Version="9.2.1" />
		<PackageReference Include="Microsoft.Orleans.Server" Version="9.2.1" />
	</ItemGroup>
</Project>
