<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
      <PackageReference Include="Cracker.EfCore" />
      <PackageReference Include="Cracker.EventBus" />
      <PackageReference Include="Cracker.Serilog" />
      <PackageReference Include="Cracker.Utils" />
      <PackageReference Include="Cracker.IdentityServer" />
	  <ProjectReference Include="..\Fancyx.Shared\Fancyx.Shared.csproj" />
	</ItemGroup>
</Project>
