<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
      <PackageReference Include="Fancyx.EfCore" Version="1.0.4" />
      <PackageReference Include="Fancyx.EventBus" Version="1.0.4" />
      <PackageReference Include="Fancyx.Serilog" Version="1.0.0" />
      <PackageReference Include="Fancyx.Utils" Version="1.0.0" />
	  <ProjectReference Include="..\Fancyx.Shared\Fancyx.Shared.csproj" />
	</ItemGroup>
</Project>
