<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StackExchange.Redis" Version="2.9.11" />
		<PackageReference Include="RedLock.net" Version="2.3.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Fancyx.Core\Fancyx.Core.csproj" />
	</ItemGroup>
</Project>
