<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Gen\*">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Fancyx.EventBus" Version="1.0.4" />
		<PackageReference Include="Fancyx.Cache" Version="1.0.4" />
		<ProjectReference Include="..\Fancyx.Shared\Fancyx.Shared.csproj" />
		<ProjectReference Include="..\Fancyx.Shared.Proto\Fancyx.Shared.Proto.csproj" />
		<ProjectReference Include="..\Fancyx.Shared.Logger\Fancyx.Shared.Logger.csproj" />
		<ProjectReference Include="..\Fancyx.Admin.EfCore\Fancyx.Admin.EfCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="MiniExcel" Version="1.41.3" />
		<PackageReference Include="IP2Region.Net" Version="2.0.2" />
		<PackageReference Include="Coravel" Version="6.0.2" />
		<PackageReference Include="JinianNet.JNTemplate" Version="2.4.3" />
	</ItemGroup>
</Project>
