<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Gen\*">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Cracker.Caching" />
		<PackageReference Include="Cracker.Scheduler" />
		<ProjectReference Include="..\Fancyx.Shared\Fancyx.Shared.csproj" />
		<ProjectReference Include="..\Fancyx.Shared.Proto\Fancyx.Shared.Proto.csproj" />
		<ProjectReference Include="..\Fancyx.Admin.EfCore\Fancyx.Admin.EfCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="MiniExcel" />
		<PackageReference Include="IP2Region.Net" />
		<PackageReference Include="JinianNet.JNTemplate" />
	</ItemGroup>
</Project>
