<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Fancyx.Core" Version="1.0.4" />
		<PackageReference Include="Fancyx.Cache" Version="1.0.4" />
		<PackageReference Include="Fancyx.Consul" Version="1.0.0" />
		<PackageReference Include="Fancyx.SnowflakeId" Version="1.0.0" />
		<PackageReference Include="Fancyx.Utils" Version="1.0.0" />
		<ProjectReference Include="..\Fancyx.Shared.Proto\Fancyx.Shared.Proto.csproj" />
		<ProjectReference Include="..\Fancyx.Shared\Fancyx.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.64.0" />
		<PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.64.0" />
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.64.0" />
		<PackageReference Include="Google.Protobuf" Version="3.32.0" />
		<PackageReference Include="Calzolari.Grpc.AspNetCore.Validation" Version="8.1.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
	</ItemGroup>
</Project>
