<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
	  <PackageReference Include="Fancyx.Consul" Version="1.0.0" />
	  <PackageReference Include="Fancyx.Serilog" Version="1.0.0" />
  </ItemGroup>

</Project>
